# Generated by Django 6.0.5 on 2026-07-31 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(blank=True, max_length=200, null=True)),
                ('rasm', models.ImageField(upload_to='sartaroshlar/')),
                ('tajriba', models.PositiveIntegerField()),
                ('reyting', models.FloatField(default=5.0)),
                ('narx', models.PositiveIntegerField()),
                ('tavsif', models.TextField(blank=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_ismi', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField()),
                ('sartarosh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
