# Generated by Django 6.0.5 on 2026-07-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rasm',
            field=models.ImageField(upload_to='barberlar/'),
        ),
    ]
