# Generated by Django 6.1 on 2026-08-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rasm',
        ),
    ]
