# Generated by Django 6.1 on 2026-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_product_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rasm',
            field=models.ImageField(default='product/default.jpg', upload_to='barberlar/'),
            preserve_default=False,
        ),
    ]
